baseurl = "https://uncoast-unconf.netlify.com" # need to change once get rbind.io set up.
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "Uncoast Unconf"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "#uncoastUnconf"
    [[params.navbar.menu]]
      link = "/"
      text = "HOME"
    [[params.navbar.menu]]
      link = "#about"
      text = "ABOUT"
    [[params.navbar.menu]]
      link = "#sponsors"
      text = "SPONSORS"
#    [[params.navbar.menu]]
#      link = "http://bit.ly/uncoastUnconf19"
#      text = "APPLY"
    [[params.navbar.menu]]
      link = "mailto:sctyner@iastate.edu"
      text = "CONTACT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2019/wiki/Code-of-Conduct" # temp. work-around until I figure out the internal linking thing.
      text = "CODE OF CONDUCT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2019/wiki/FAQ"
      text = "FAQ"

  # Header
  [params.header]
    title = "The Uncoast Unconference"
    text = "Bringing R users and developers together in flyover country.<br>See what we'll be working on, and contribute a project idea on [Github](https://github.com/uncoast-unconf/uu-2019/issues)!"
    [params.header.image]
      path = "images/templogo.png"
      alt = "Uncoastal"
#    [params.header.button]
#      link = "http://bit.ly/uncoastUnconf19" # in draft status rn.
#      text = "Apply here!"
      # want button to have color #135FB2 and color #BEC0C3 on hover

  # about
  [params.features]
    title = "About"
    [params.features.image]
      path = "images/map.png"
      alt = "Location"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-calendar2"
      title = "When"
      text = "April 14-16, 2019"
    [[params.features.left]]
      icon = "tf-map2"
      title = "Where"
      text = "John Deere Financial in Des Moines, IA"
    [[params.features.left]]
      icon = "tf-ion-person-add"
      title = "Who"
      text = "You!"
    [[params.features.left]]
      icon = "tf-alarmclock"
      title = "Deadline"
      text = "Apply by February 5 at 5pm"
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 14"
      text = "An optional 'Day Zero' workshop for learning how to write R packages and collaborate with Github."
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 15"
      text = "Day 1: Start with some introductions, form project groups, and go!"
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 16"
      text = "Day 2: Continue to work on projects, group discussions, report out, dinner as a group."

  [params.promo]
    title = "What is an unconference?"
    text = "Unlike a conference with scheduled sessions and the mere hope of future collaboration, at an unconference, the collaboration happens in real time! Modeled on <a href='https://ropensci.org/blog/2018/06/05/unconf18/' style='color: #fff;text-decoration:underline;'>rOpenSci unconfs</a>, at the Uncoast Unconf, R users and developers of all different backgrounds and levels will come together for two days to collaborate on exciting data science projects. In addition, we will be hosting a Day 0 workshop for participants who are new to package development and collaboration with Github. For more on this type of unconference, see <a href='https://ropensci.org/blog/2017/11/17/unconf-sixtips/' style='color: #fff;text-decoration:underline;'>this post</a>"
    [params.promo.image]
      path = "images/karthik-runconf17.png"
      alt = "What is an unconf?"
      text = "Photo credit: Karthik Ram, <a href='https://ropensci.org/' style='color: #fff;text-decoration:underline;'>rOpenSci</a>"

  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    # How would you describe your participants? What are they bringing to your event
    text = "Our participants represent the wide variety of skills and experience of all R users, from beginners to a member of R-Core. They come from industry, academia, and government,  and we are proud to bring such a diverse group of R users and developers together in the middle of America."
    directory = "images/team"
    # All team member's pictures should be stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]] # create one of these for each of your participants
      name = "Yihui Xie"
      position = "RStudio"
      livesIn = "Nebraska"
      img = "yihui-headshot.png" # e.g. firstname-lastname.png 
      twitter = "xieyihui" # handle only. (not a URL, no @)
      github = "yihui" # handle only. (not a URL, no @)
      url = "https://yihui.name/en/" # A URL 
   
    [[params.team.members]] # create one of these for each of your participants
      name = "Amelia McNamara"
      position = "University of St. Thomas"
      livesIn = "Minnesota"
      img = "amelia-headshot.png" # e.g. firstname-lastname.png 
      twitter = "AmeliaMN" # handle only. (not a URL, no @)
      github = "AmeliaMN" # handle only. (not a URL, no @)
      url = "http://www.amelia.mn/" # A URL   
      
    [[params.team.members]]
      name = "Carson Sievert"
      position = "RStudio"
      livesIn = "Minnesota"
      img = "carson-headshot.png"
      twitter = "cpsievert"
      github = "cpsievert"
      url = "https://cpsievert.me/"

    [[params.team.members]]
      name = "Winston Chang"
      position = "RStudio"
      livesIn = "Minnesota"
      img =  "winston-headshot.png"
      twitter = "winston_chang"
      github = "wch"

    [[params.team.members]]
      name = "Luke Tierney"
      position = "University of Iowa"
      livesIn = "Iowa"
      img = "luke-headshot.png"      
      website = "http://homepage.divms.uiowa.edu/~luke/"
      
    [[params.team.members]]
      name = "Haley Jeppson"
      position = "Iowa State University"
      livesIn = "Iowa"
      img = "haley-headshot.png"
      github = "haleyjeppson"
      twitter = "heyhayhay__"



  [params.gallery]
    title = "Other Unconfs Past & Future"
    subtitle = "If you're in the Chicago area, also check out our sister event happening in March, the"
    link = "https://chirunconf.github.io/"
    linktext = "Chicago R Unconference."
    text = "Thanks to Mauro Lepore and Nistara Randhawa for the photos from previous rOpenSci Unconferences!"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["ropensci-unconf17-checkers-nistara-randhawa.png", "mauro-runconf18-1.png", "mauro-runconf18-5.png", "mauro-runconf18-2.png", "mauro-runconf18-3.png", "mauro-runconf18-6.png", "mauro-runconf18-7.png"]

  [params.call_to_action]
    title = "Thank you to our sponsors!"
    text = "If you have questions about sponsorship or your organization is interested in becoming a sponsor, please email Sam Tyner at sctyner [at] iastate [dot] edu."
    directory = "images/sponsors"
    images = ["rstudio.png", "rconsortium.png", "csafe.png", "schneider.png"]


  [params.testimonials]
    title = "Organizers"
    [[params.testimonials.blocks]]
      text = "Sam earned her PhD in Statistics from Iowa State University in 2017. Her primary research interests are data visualization and forensic statistics. She writes about both of these things on her <a href='https://sctyner.github.io/'>website</a>."
      name = "Sam Tyner"
      position = "Postdoc Research Associate, Iowa State University"
      image = "images/sam-headshot.png"
    [[params.testimonials.blocks]]
      text = "Sam holds an MS in statistics from Iowa State University. Before starting his current position, he worked in applied analytics roles within John Deere Worldwide Parts and Global Order Fulfillment."
      name = "Sam Helmich"
      position = "Principal Data Scientist, John Deere Intelligent Solutions Group"
      image = "images/samh-headshot.png"
    [[params.testimonials.blocks]]
      text = "Ian's background is in Mechanical Engineering and Computational Fluid Dynamics. As Schneider Electric became more data-centric, he learned R, and soon became an R visualization enthusiast. Since joining the ISU Statistical Graphics Working Group, Ian has become an R expert!"
      name = "Ian Lyttle"
      position = "Data Scientist, Schneider Electric"
      image = "images/ian-headshot.png"
    [[params.testimonials.blocks]]
      text = "Susan got her PhD from Iowa State University in 2015. She is currently working on research in statistical graphics and forensic statistics."
      name = "Susan Vanderplas"
      position = "Research Assistant Professor, Iowa State University"
      image = "images/susan-headshot.png"
    [[params.testimonials.blocks]]
      text = "Angela has a background in spatial econometrics and is currently building out spatial analysis resources for applied social science research. She is a proud R-Lady and data science community builder. Learn more about Angela on her <a href='https://angela-li.github.io/'>website</a>."
      name = "Angela Li"
      position = "R Spatial Advocate, University of Chicago"
      image = "images/angela-headshot.png"  
    [[params.testimonials.blocks]]
      text = "Heike's primary research interests are Data Visualization, Multivariate Categorical Data Analysis, Statistical Computing, Exploratory Data Analysis and Interactive Statistical Graphics. She is also a member of the ISU Data Science Curriculum Committee."
      name = "Heike Hofmann"
      position = "Professor of Statistics, Iowa State University"
      image = "images/heike-headshot.png"
#    [params.testimonials.button]
#     link = "http://bit.ly/uncoastUnconf19"
#      text = "Apply here!"

  # Footer uses navbar data
